function() {
    var size = jsbuildRuntimeBasePackage.console.ui.getSize();

    var console = document.createElement("div");
    console.style.fontSize = "12px";
    console.style.fontWeight = "bold";
    console.style.color = "#fff";
    console.style.backgroundColor = "#000";
    console.style.padding = "0px";
    console.style.margin = "0px";
    console.style.position = "fixed";
    console.style.zIndex = 999;
    console.style.overflow = "auto";
    console.style.width = "100%";
    console.style.height = "28%";
    console.style.left = "0px";
    console.style.top = "66%";
    console.readOnly = true;
    console.id = "osecta";
    document.getElementsByTagName("body").item(0).appendChild(console);
    console = document.createElement("div");
    console.style.fontSize = "12px";
    console.style.fontWeight = "bold";
    console.style.color = "#fff";
    console.style.backgroundColor = "#666";
    console.style.padding = "0px";
    console.style.margin = "0px";
    console.style.position = "fixed";
    console.style.zIndex = 999;
    console.style.width = "100%";
    console.style.left = "0px";
    console.style.height = "6%";
    console.style.top = "60%";
    console.id = "osehbc";
    console.innerHTML = "<h4 style='padding:0px;margin:0px' align='center'>JSB Console</h4><button style='padding:0px;margin:0px;float:right;position:absolute;top:0%;width:8%;left:90%' id='consoleShowHideButton'>Show/Hide</button>";
    document.getElementsByTagName("body").item(0).appendChild(console);
    console = document.createElement("input");
    console.style.fontSize = "12px";
    console.style.fontWeight = "bold";
    console.style.color = "#fff";
    console.style.backgroundColor = "#000";
    console.style.padding = "0px";
    console.style.margin = "0px";
    console.style.position = "fixed";
    console.style.zIndex = 999;
    console.style.width = size.width - 100 + "px";
    console.style.left = "100px";
    console.style.height = "6%";
    console.style.top = "94%";
    console.id = "osecin";
    document.getElementsByTagName("body").item(0).appendChild(console);
    console = document.createElement("input");
    console.style.fontSize = "12px";
    console.style.fontWeight = "bold";
    console.style.color = "#fff";
    console.style.backgroundColor = "#000";
    console.style.padding = "0px";
    console.style.margin = "opx";
    console.style.position = "fixed";
    console.style.zIndex = 999;
    console.style.width = "100px";
    console.style.left = "0px";
    console.style.height = "6%";
    console.style.top = "94%";
    console.readOnly = true;
    console.value = "Command ->";
    console.id = "ccmdsp";
    document.getElementsByTagName("body").item(0).appendChild(console);
}